---
# lnmp

- name: install lnmp
  hosts: webservers
  remote_user: root
  roles:
    - nginx
    - php
    #- laravel

#- name: install mysql
#  hosts: dbservers
#  remote_user: root
#  roles:
#    - mysql
