---

- name: set apt sources  
  copy: src=sources.list dest=/etc/apt/sources.list

- name: add nginx_signing.key  
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key 
    state: present

- name: apt-get update  cache 
  shell: "{{ item }}"
  with_items:
   - apt update 


- name: install git
  apt: 
   name: git
   state: present

#解决乱码问题开始
- name: luanma 
  apt: 
   name: language-pack-zh-hans
   state: present


- name: check LANG="zh_CN.UTF-8" to /etc/environment
  shell: awk '/LANG="zh_CN\.UTF-8"/' /etc/environment
  register: environment_LANG


- name: add  LANG="zh_CN.UTF-8" to /etc/environment
  shell: echo 'LANG="zh_CN.UTF-8"' >> /etc/environment
  when: environment_LANG.stdout == ''

#解决乱码问题结束

