---
- name: python-software-properties
  apt: 
   name: python-software-properties
   state: present

- name: add php ppa repo
  apt_repository:
    repo: ppa:ondrej/php


- name: Install php
  apt: name={{ item }}  state=present
  with_items:  
   - php{{ lang_php_ver }}-cli
   - php{{ lang_php_ver }}-fpm
   - php{{ lang_php_ver }}-dev

- name: configure php-fpm
  copy: src=www.conf dest=/etc/php/7.1/fpm/pool.d/www.conf
  changed_when: yes
  notify: 
   - restart php-fpm
