---
- stat: path={{ lang_php_prefix }}/bin/php
  register: lang_php_bin

- import_tasks: install.yml
  when: not lang_php_bin.stat.exists


#- name: Install php extensions
#  apt: >-
#    name={{ item }}
#    state=present
#  with_items: '{{ lang_php_extensions }}'
