---
- stat: path={{ lang_php_prefix }}/bin/php
  register: lang_php_bin

- include: install.yml
  when: not lang_php_bin.stat.exists


- name: Install php extensions
  yum: >-
    name={{ item }}
    state=present
  with_items: '{{ lang_php_extensions }}'
 
 
